### ISSUE TITLE
标注并没到发丝级别的抠图

### ISSUE THREAD

**Issue by lan2720** [aisegmentcn/matting_human_datasets#3]
RT
这种粗粒度的抠图还是没法用于matting的训练了，用于segmentation倒可以，是否有计划放出更细粒度的抠图数据？谢谢！

**Comment by wodsoe** [comment]
这种数据训练出来的，效果不行吗？

**Comment by aisegmentcn** [comment]
用这个数据集训练的效果可以去我们官网体验：www.aisegment.com
如果您需要更高的效果，我建议你这样处理：把alpha转成trimap，然后再做一次传统的图像matting方法，用新matting数据看看。

**Comment by lan2720** [comment]
@aisegmentcn 你们官网测试demo一直连接错误

**Comment by aisegmentcn** [comment]
@lan2720 官网可以正常使用啊。或者您在微信里搜：标准证件照。也能体验。
